export const SET_BUSY = "SET_BUSY"
export const UNSET_BUSY = "UNSET_BUSY"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAILURE = "LOGOUT_FAILURE"

export const GEOLOCATION_RETRIEVAL_REQUEST = "GEOLOCATION_RETRIEVAL_REQUEST"
export const GEOLOCATION_RETRIEVAL_SUCCESS = "GEOLOCATION_RETRIEVAL_SUCCESS"
export const GEOLOCATION_RETRIEVAL_FAILURE = "GEOLOCATION_RETRIEVAL_FAILURE"

export const FIELDS_RETRIEVAL_REQUEST = "FIELDS_RETRIEVAL_REQUEST"
export const FIELDS_RETRIEVAL_SUCCESS = "FIELDS_RETRIEVAL_SUCCESS"
export const FIELDS_RETRIEVAL_FAILURE = "FIELDS_RETRIEVAL_FAILURE"

export const CROPS_RETRIEVAL_REQUEST = "CROPS_RETRIEVAL_REQUEST"
export const CROPS_RETRIEVAL_SUCCESS = "CROPS_RETRIEVAL_SUCCESS"
export const CROPS_RETRIEVAL_FAILURE = "CROPS_RETRIEVAL_FAILURE"

export const ADD_FIELD_REQUEST = "ADD_FIELD_REQUEST"
export const ADD_FIELD_SUCCESS = "ADD_FIELD_SUCCESS"
export const ADD_FIELD_FAILURE = "ADD_FIELD_FAILURE"

export const DELETE_FIELD_REQUEST = "DELETE_FIELD_REQUEST"
export const DELETE_FIELD_SUCCESS = "DELETE_FIELD_SUCCESS"
export const DELETE_FIELD_FAILURE = "DELETE_FIELD_FAILURE"

export const ADD_CROP_REQUEST = "ADD_CROP_REQUEST"
export const ADD_CROP_SUCCESS = "ADD_CROP_SUCCESS"
export const ADD_CROP_FAILURE = "ADD_CROP_FAILURE"

export const DELETE_CROP_REQUEST = "DELETE_CROP_REQUEST"
export const DELETE_CROP_SUCCESS = "DELETE_CROP_SUCCESS"
export const DELETE_CROP_FAILURE = "DELETE_CROP_FAILURE"

export const SATELLITE_INSIGHTS_RETRIEVAL_REQUEST = "SATELLITE_INSIGHTS_RETRIEVAL_REQUEST"
export const SATELLITE_INSIGHTS_RETRIEVAL_SUCCESS = "SATELLITE_INSIGHTS_RETRIEVAL_SUCCESS"
export const SATELLITE_INSIGHTS_RETRIEVAL_FAILURE = "SATELLITE_INSIGHTS_RETRIEVAL_FAILURE"

export const AGRIBOT_INSIGHTS_RETRIEVAL_REQUEST = "AGRIBOT_INSIGHTS_RETRIEVAL_REQUEST"
export const AGRIBOT_INSIGHTS_RETRIEVAL_SUCCESS = "AGRIBOT_INSIGHTS_RETRIEVAL_SUCCESS"
export const AGRIBOT_INSIGHTS_RETRIEVAL_FAILURE = "AGRIBOT_INSIGHTS_RETRIEVAL_FAILURE"
